* Revert what Revision 3599 changed in only QwSubsystemArrayParity.cc in order to run qwparity analyzer properly.
* R3599 returns tons of the following errors, 

yp_targ: published-value
Error: Could not publish variable qwk_md1neg in subsystem Main Detector!
Error: Not all variables for Main Detector could be published!
Error: Attempting to publish existing variable key!
List of published values:
e_targ: published-value
q_targ: published-value
qwk_3c16_effectivecharge: published-value
qwk_md1neg: qwk_md1-
qwk_md1pos: qwk_md1+
qwk_md2neg: qwk_md2-
qwk_md2pos: qwk_md2+
qwk_md3neg: qwk_md3-
qwk_md3pos: qwk_md3+
qwk_md4neg: qwk_md4-
qwk_md4pos: qwk_md4+
qwk_md5neg: qwk_md5-
qwk_md5pos: qwk_md5+
qwk_md6neg: qwk_md6-
qwk_md6pos: qwk_md6+
qwk_md7neg: qwk_md7-
qwk_md7pos: qwk_md7+
qwk_md8neg: qwk_md8-
qwk_md8pos: qwk_md8+
x_targ: published-value
xp_targ: published-value
y_targ: published-value
yp_targ: published-value

* Thus, I revert or overwrite Copy constructor and Copy functions what Revision 3599 changed in only QwSubsystemArrayParity.cc in order to run qwparity analyzer. Note that I don't revert QwSubsystemArray.cc.

* Friday, December  2 11:41:54 EST 2011, jhlee




git-svn-id: https://qweaksvn.jlab.org/repos/QwAnalysis/trunk@3625 b9700a98-9937-0410-b777-f318d6eb5bff