* Add QwSSQLS.h in all binary sources - qwanalysis_adc qwanalysis_beamline   qwanalysis_mysql qwtracking - we want to compile so that we can remove the   following errors
  ./lib/libQw.so: undefined reference to `beam::names'
  ./lib/libQw.so: undefined reference to `analysis::table_'
  ./lib/libQw.so: undefined reference to `analysis::names'
  ./lib/libQw.so: undefined reference to `run::names'
  ./lib/libQw.so: undefined reference to `run::table_'
  ./lib/libQw.so: undefined reference to `beam::table_'
  collect2: ld returned 1 exit status
  make[1]: *** [bin/qwanalysis_beamline] Error 1


* Replace 'size_t' with 'UInt_t' because size() returns unsigned integral type.




git-svn-id: https://qweaksvn.jlab.org/repos/QwAnalysis/branches/spayde@831 b9700a98-9937-0410-b777-f318d6eb5bff