* encapsulate some functionalities that are   valid for only F1TDC into MQwF1TDC as possible as I can   at this moment. (This will be improved later I hope)
* temporarily suppress all warning messages except
  "event number" discrepancy. In that case, one can 
  see the following message.

Error: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error:        REQUIRE a reset of the F1TDC board at ROC11 Slot 4
Error:        Please contact (a) Qweak DAQ expert(s) immediately.
Error: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 


* some dummy functions are introduced in MQwV775TDC class
  so as to match them with MQwF1TDC class




git-svn-id: https://qweaksvn.jlab.org/repos/QwAnalysis/trunk@1006 b9700a98-9937-0410-b777-f318d6eb5bff