Cargo-cult change to restore compilation with default options.
As it was, compiling without setting some restriction on EXES
generated the error:

	ld: duplicate symbol DefineOptionsParity(QwOptions&)
		in ./lib/libQw.dylib(QwComptonElectronDetector.o)
		and Parity/main/QwParity.o

This function is defined in QwOptionsParity.h, which I guess should
only be loaded from source files defining executables.  This seems to
be a better header to depend on.

git-svn-id: https://qweaksvn.jlab.org/repos/QwAnalysis/trunk@2263 b9700a98-9937-0410-b777-f318d6eb5bff