Changed some error messages that were being displayed in Red in to warnings inside the helicity pattern calsss and helicity class. This use to confuse shift takers when the QwFeedback is running. They think its broaken because of the pattern mismatch warning that naturally happen at the begining of each analysis. I am not saying they should avoid the warnings. Should figure out a better way to do this for the running of QwFeedback..For now, I hope this is fine
Before:
Error: QwHelicityPattern::CalculateAsymmetry:  Helicity should be 1 or 0 but is -9999; Asymmetry computation aborted!

After:
Warning: QwHelicityPattern::CalculateAsymmetry:  Helicity should be 1 or 0 but is -9999; Asymmetry computation aborted!



git-svn-id: https://qweaksvn.jlab.org/repos/QwAnalysis/trunk@2425 b9700a98-9937-0410-b777-f318d6eb5bff