* improve the bcm calibration, can find a peak  if the signal has no ramping currents
* fixed missing analysis_id in mysql db query in QwBlinder
  Parity/src/QwBlinder.cc:881: In member function 'void QwBlinder::FillDB(QwDatabase*, TString)':
  Parity/src/QwBlinder.cc:881:warning: too many arguments for format

* initialized variable in QwScaler_Channel and VQwDataElement to remove unreasonable errors by valgrind

  valgrind qwparity -r 9273 -e0:1000 (1000 event)

     Before :: ERROR SUMMARY: 163153 errors from 140 contexts (suppressed: 671904 from 21)  
     After  :: ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 671904 from 21)

  reduece possibly lost and increase still reachable (1000 events)   
  	  Before : 	possibly lost: 2,735,052 bytes in 47,687 blocks
	  	 	still reachable: 1,457,662 bytes in 26,202 blocks
          After  :      possibly lost: 2,705,325 bytes in 46,898 blocks
                        still reachable: 1,487,389 bytes in 26,991 blocks

* added several debug features to understand class behavior.

Friday, January 21 13:59:47 EST 2011, jhlee



git-svn-id: https://qweaksvn.jlab.org/repos/QwAnalysis/trunk@2436 b9700a98-9937-0410-b777-f318d6eb5bff