* Add F1TDC header and its object (fF1TDC) in QwRaster.h   in order to remove the following error   Tracking/src/QwRaster.cc: In member function ‘Int_t QwRaster::RegisterSlotNumber(UInt_t)’:   Tracking/src/QwRaster.cc:684: error: ‘fF1TDC’ was not declared in this scope   make[1]: *** [Tracking/src/QwRaster.o] Error 1
* Resurrected original FillRawTDCWord to remove vector range errors.

* Turned off QwDriftChamberVDC::AddChannelDefinition ( const UInt_t plane, const UInt_t wire ),
  because it is valid for Region 2.

* Removed time_shift= -8929.0, because the time will be corrected via t0 correction
  in Region 3



git-svn-id: https://qweaksvn.jlab.org/repos/QwAnalysis/trunk@1466 b9700a98-9937-0410-b777-f318d6eb5bff