* fix the following error temporarily (Debian lenny, 64bit)
  Parity/src/QwBeamLine.cc: In member function ‘virtual void QwBeamLine::FillDB(QwDatabase*, TString)’:
  Parity/src/QwBeamLine.cc:1341: error: conversion from ‘mysqlpp::Query’ to ‘bool’ is ambiguous

* I think, this might be a version conflict between MySQL++. 



git-svn-id: https://qweaksvn.jlab.org/repos/QwAnalysis/trunk@905 b9700a98-9937-0410-b777-f318d6eb5bff